# baseURL = 'https://purposeunknown.xyz/'
languageCode = 'en-us'
title = 'Vee (PurposeUnknown)'
theme = "poison"
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries
contentDir = "themes/poison/content"

# NOTE: If using Disqus as commenting engine, uncomment and configure this line
# disqusShortname = "yourDisqusShortname"

[params]
    brand = "Vee (PurposeUnknown)"                      # name of your site - appears in the sidebar
    # remote_brand_image = '' # path to a remote file
    brand_image = "/images/vee-pfp.jpg"    # path to the image shown in the sidebar
    description = "random ramblings from a techno-wanderer" # Used as default meta description if not specified in front matter
    dark_mode = false                      # optional - defaults to false
    # favicon = "favicon.png"             # path to favicon (defaults to favicon.png)

    front_page_content = ["posts"] # Equivalent to the default value, add page bundle names to include them on the front page.

    # MENU PLACEHOLDER
    # Menu dict keys:
        # Name:         The name to display on the menu.
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
    
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]

    # Links to your socials.  Comment or delete any you don't need/use. 
    bluesky_url = "https://bsky.app/profile/purposeunknown.xyz"
    vrchat_url = "https://vrchat.com/home/user/usr_9a126e50-56b0-497e-bea4-ecee3d9cf7c0"
    # discord_url = "https://discord.com"
    # email_url = "mailto://user@domain"
    # facebook_url = "https://facebook.com"
    # flickr_url = "https://flickr.com"
    github_url = "https://github.com/PurposeUnknown"
    # gitlab_url = "https://gitlab.com"
    # instagram_url = "https://instagram.com"
    # linkedin_url = "https://linkedin.com"
    # mastodon_url = "https://mastodon.social"
    # matrix_url = "https://matrix.org"
    # telegram_url = "https://telegram.org"
    # tryhackme_url = "https://tryhackme.com"
    # twitter_url = "https://twitter.com"
    # x_url = "https://x.com"
    # xmpp_url = "https://xmpp.org"
    # youtube_url = "https://youtube.com"
    # signal_url = "purposeunknown.01"
    

    # NOTE: If you don't want to use RSS, comment or delete the following lines
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    # rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    # rss_section = "posts"

    # Hex colors for your sidebar.
    moon_sun_background_color = "#3A1C71"   # default is #515151
    moon_sun_color = "#ECEFF1"                 # default is #FFF
    sidebar_a_color = "#D1C4E9"                # default is #FFF
    sidebar_bg_color = "#3A1C71"            # default is #202020
    sidebar_h1_color = "#ECEFF1"               # default is #FFF
    sidebar_img_border_color = "#D1C4E9"    # default is #515151
    sidebar_p_color = "#B39DDB"             # default is #909090
    sidebar_socials_color = "#ECEFF1"          # default is #FFF

    # Hex colors for your sidebar.
    # moon_sun_background_color = "#B49FC9"   # default is #515151
    # moon_sun_color = "#F5E9FF"                 # default is #FFF
    # sidebar_a_color = "#EDE0FF"                # default is #FFF
    # sidebar_bg_color = "#2E1A47"            # default is #202020
    # sidebar_h1_color = "#EAD6FF"               # default is #FFF
    # sidebar_img_border_color = "#6A4C93"    # default is #515151
    # sidebar_p_color = "#B49FC9"             # default is #909090
    # sidebar_socials_color = "#EDE0FF"          # default is #FFF


    # Hex colors for your content in light mode.
    code_color = "#1C0B2D"                     # default is #000
    code_background_color = "#F1EAF9"       # default is #E5E5E5
    code_block_color = "#FSF0FF"               # default is #FFF
    code_block_background_color = "#3D2B52" # default is #272822
    content_bg_color = "#F9F4FF"            # default is #FAF9F6
    date_color = "#6E579E"                  # default is #515151
    link_color = "#8A63D2"                  # default is #268BD2
    list_color = "#7C5B9C"                  # default is #5A5A5A
    post_title_color = "#422F59"            # default is #303030
    table_border_color = "#EADDFB"          # default is #E5E5E5
    table_stripe_color = "#F5F0FF"          # default is #F9F9F9
    text_color = "#2B1E3B"                     # default is #222

    # Hex colors for your content in dark mode
    code_color_dark = "#F5E9FFF"                        # default is #FFF
    code_background_color_dark = "#5A417F"          # default is #515151
    code_block_color_dark = "#F5E9FF"                  # default is #FFF
    code_block_background_color_dark = "#3D2B52"    # default is #272822
    content_bg_color_dark = "#1C102B"               # default is #121212
    date_color_dark = "#B49FC9"                     # default is #9A9A9A
    link_color_dark = "#A482D8"                     # default is #268BD2
    list_color_dark = "#BFA9D9"                     # default is #9D9D9D
    post_title_color_dark = "#EAD6FF"               # default is #DBE2E9
    table_border_color_dark = "#64AC93"             # default is #515151
    table_stripe_color_dark = "#2E1A47"             # default is #202020
    text_color_dark = "#EAD6FF"                        # default is #EEE

    # NOTE: If using Remark42 as commenting engine, uncomment and configure these lines
    # remark42 = true
    # remark42_host = "https://yourhost.com"
    # remark42_site_id = "your_site_id"

    # NOTE: The following three params are optional and are used to create meta tags + enhance SEO.
    # og_image = ""                       # path to social icon - front matter: image takes precedent, then og_image, then brand_url
                                          # this is also used in the schema output as well. Image is resized to max 1200x630
                                          # For this to work though og_image and brand_url must be a path inside the assets directory
                                          # e.g. /assets/images/site/og-image.png becomes images/site/og-image.png
    # publisher_icon = ""                 # path to publisher icon - defaults to favicon, used in schema

[taxonomies]
    series = 'series'
    tags = 'tags'
